initial commit
fortinet-fortisoar/solution-pack-fortindr-cloud pull request #1
Opened 2023-03-30 11:13 UTC by cs-prerna-joshi

PMDB: https://pmdb.fortinet.com/ProjectManagement/editprojects.php?id=24664 

UTC:
**Get FortiNDR Detection Scenario**
- validated Alerts get created based on FortiNDR Cloud Detection in FortiSOAR.
- validated after running the Get Detection Events PB , events get appended in source data of alert and indicators got created.
- also checked the asset got linked to alert.

2023-03-30 11:32 UTC, cs-suyog-jinturkar commented on info.json
> +    "help": null,
help link to .md file

2023-03-30 11:33 UTC, cs-suyog-jinturkar commented on info.json
> +    "description": "This FortiSOAR Solution Pack for FortiNDR Cloud offering helps customers to readily orchestrate the investigation of detection.",
It will be great if we can add detailed desc here

2023-03-30 11:33 UTC, cs-suyog-jinturkar commented on info.json
> +    "supportInfo": null,
Fortinet Support

2023-03-30 11:36 UTC, cs-suyog-jinturkar commented on modules/scenario/mmd.json
We should not include scenario mmd.json here. Any reason for its inclusion in this SP?

2023-03-30 11:42 UTC, cs-rohit-khune requested changes

2023-03-30 11:42 UTC, cs-rohit-khune commented on info.json
> +    "help": null,
Please add the doc link: https://github.com/fortinet-fortisoar/solution-pack-fortindr-cloud/blob/release/1.0.0/README.md

2023-03-30 11:42 UTC, cs-rohit-khune commented on info.json
> +        "globalVariables": [
Please remove globaVariables

2023-03-30 11:42 UTC, cs-rohit-khune commented on info.json
> +        "modules": {
Please remove scenario module

2023-03-30 11:42 UTC, cs-rohit-khune commented on modules/scenario/mmd.json
> +{
Please remove scenario mmd.json

2023-03-30 11:42 UTC, cs-rohit-khune commented on modules/scenario/mmd.json
Remove this file

2023-03-30 11:42 UTC, cs-rohit-khune commented on playbooks/globalVariables.json
This should be an empty list. Please remove the global variable

2023-03-30 11:42 UTC, cs-rohit-khune commented on records/scenario/scenario0001.json
> +        "createdAlertsID": "[\"\/api\/3\/alerts\/c8346414-6a30-43f6-bc48-c8675c7b0eb1\"]",
createdAlertsID value should be null. Please remove alert IRI from the scenario record

2023-03-30 12:17 UTC, cs-rohit-khune commented on playbooks/02 - Use Case - FortiNDR Cloud/Fortinet FortiNDR Cloud > Fetch Detection Events.json
> +    "recordTags": []
Please add `ManualAction` tag to the playbook

2023-03-31 06:28 UTC, cs-rohit-khune approved these changes

2023-03-31 06:28 UTC, cs-rohit-khune approved these changes
Approved

2023-03-31 07:06 UTC, cs-suyog-jinturkar approved these changes

2023-03-31 07:06 UTC, merged